#-------------------------------
# General Site Settings

title: Beyonsei
logo: 
author: themefisher
description: this is meta description
email: info@yonsei.ac.kr
phone: +82-2-2123-5000
address: 50, Yonsei-ro, Seodaemun-gu, Seoul, Republic of Korea
copyright: Copyright &copy; 2020 Yonsei University 

menu:
- {name: About, link: '/meu4300-01/about'}                   # About
- {name: Robot, link: '/meu4300-01/blog'}                    # Blog 
- {name: Project, link: '/meu4300-01/portfolio'}             # Portfolio
- {name: Contact, link: '/meu4300-01/contact'}               # Contact


#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics: # UA-XXXXXX-X


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Hero Section

hero:
  hero-title: Mobile Modulus Market(3M)

social:
- {icon: "ti-facebook", link: "#"}
- {icon: "ti-instagram", link: "#"}
- {icon: "ti-dribbble", link: "#"}
- {icon: "ti-twitter", link: "#"}


#-------------------------------
# About (Section and Page)

# About Section
blurb:
   본 프로젝트는 연세대학교 기계공학부 창의제품설계(종합설계) 과목의 일환으로 시작된 것으로 자율주행과 공유경제 두 가지 키워드를 중심으로 모듈화된 로봇 플랫폼을 이용하여 상품을 판매하고 홍보하는 목적을 가지고 시작되었습니다.

blurb-btn-link: '/about'
blurb-btn-name: know more


# About Page

# Work Process Section
work-process:
  - title : "Brainstorming"
    icon : "assets/images/icons/plan.png"
    content : "150여개의 아이디어를 브레인스토밍하여 최종적으로 ...."
    
  - title : "Design and Conceptualizae"
    icon : "assets/images/icons/design.png"
    content : "문제의식을 바탕으로 ....."
    
  - title : "Realize"
    icon : "assets/images/icons/print.png"
    content : "ROS를 활용하여... SLAM과 자율주행 기술을 구현....."


# My Team Section
team:
  - title : "이택민"
    image : "assets/images/team/member-1.png"
    designation : "Project Manager"
    
  - title : "강신욱"
    image : "assets/images/team/member-2.png"
    designation : "Graphic Designer"
    
  - title : "김묘찬"
    image : "assets/images/team/member-3.png"
    designation : "3D Designer"

  - title : "김윤태"
    image : "assets/images/team/member-3.png"
    designation : "응력 해석"
  
  - title : "김유빈"
    image : "assets/images/team/member-3.png"
    designation : "Robotics Engineer"



#-------------------------------
# Skills Section

skills-title: Skills
skills:
- {name: 3D Modeling, color: '#fdb157', value: '60%'}
- {name: Robot Control, color: '#9473e6', value: '80%'}
- {name: Graphic Design, color: '#bdecf6', value: '70%'}
- {name: Web App, color: '#ffbcaa', value: '50%'}


#-------------------------------
# Exprerience Section

experience-title: Experience
experience:
- {name: Junior UX Designer, icon: 'icon-1.png', date: 'Jan 2007 - Feb 2009', organization: 'WEBEX'}
- {name: UX & UI Designer, icon: 'icon-2.png', date: 'Mar 2009 - Aug 2014', organization: 'AUGMEDIX'}
- {name: Senior UI Designer, icon: 'icon-3.png', date: 'Sep 2014 - Present', organization: 'THEMEFISHER'}


#-------------------------------
# Education Section

education-title: Education
education:
- {name: Department of Mechanical Engineering, date: '2020', organization: 'Yonsei University'}


#-------------------------------
# Services Section

services-title: Services
services:
- {
    name: UI Design,
    icon: ti-palette,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }
- {
    name: UX Design,
    icon: ti-vector,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: true # Add true to select section
  }
- {
    name: Interaction Design,
    icon: ti-panel,
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
    active: # Add true to select section
  }



#-------------------------------
# Portfolio (Section and Page)

# Portfolio Home Section
portfolio-home-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-4.png"
    url: "#"
    
  - image : "assets/images/portfolio/item-5.png"
    url: "#"


# Portfolio Page
portfolio-label:
- {
    title : "Web Devel",
    type : "design"
  }
- {
    title : "Robotics",
    type : "branding"
  }
- {
    title : "Design",
    type : "illustration"
  }

portfolio-items:
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
     - type: "design"
     - type: "illustration"
      
  - image : "assets/images/portfolio/item-2.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-6.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-8.png"
    url: "#"
    portfolio-type:
      - type: "illustration"
      
  - image : "assets/images/portfolio/item-5.png"
    url: "#"
    portfolio-type:
      - type: "design"
      
  - image : "assets/images/portfolio/item-1.png"
    url: "#"
    portfolio-type:
      - type: "branding"
      
  - image : "assets/images/portfolio/item-3.png"
    url: "#"
    portfolio-type:
      - type: "design"
      - type: "illustration"
      - type: "branding"
      
  - image : "assets/images/portfolio/item-7.png"
    url: "#"
    portfolio-type:
      - type: "illustration"


#-------------------------------
# Testimonials Section

testimonial-items:
  - name: "Byeong Kwon, Min"
    image: "assets/images/testimonial/B.K.M.png"
    designation : "Professor"
    content : "아주 훌륭합니다 여러분. 여러분의 노고에 찬사를.....!"
    
  - name: "Dae Eun, Kim"
    image: "assets/images/testimonial/D.E.K.png"
    designation: "Professor"
    content: "이 프로젝트는 A+입니다."
    
  - name: "Hyung seok, Lee"
    image: "assets/images/testimonial/H.S.L.png"
    designation: "Professor"
    content: "<strong> ! 최고의 프로젝트입니다 ! </strong>"


#-------------------------------
# Client Slider Section

client-slider-items:
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-1.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-2.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-3.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-4.png"
    url: "#"
    
  - logo: "assets/images/clients-logo/client-logo-5.png"
    url: "#"

#-------------------------------
# Contact Section

contact-title: Contact Info
contact-email: ybkim95@yonsei.ac.kr
